### ISSUE TITLE
API compatibility is broken since 0696656 

### ISSUE THREAD

**Issue by link89** [SINGROUP/dscribe#116]
Commit [0696656 ](https://github.com/SINGROUP/dscribe/commit/069665621476ffdf1dec9b46a40a2271310cc153) introduce a change that break the compatibility. It brings a lot of error for projects that depends to `dscribe`, for example https://github.com/BingqingCheng/ASAP/issues/61

```
    self.soap = SOAP(species=self.species, rcut=self.cutoff, nmax=self.n, lmax=self.l,
TypeError: __init__() got an unexpected keyword argument 'rcut'
```

Is it intentional or accidental? I hope it could ensure backward compatibility if it is possible.

**Comment by lauri-codes** [comment]
Hi @link89!

This is indeed intentional. We wanted to start using consistent naming across all descriptors and this renaming is part of it. While ensuring backwards compatibility would not be a big problem, we wanted to avoid keeping two alternative names around for too long. I believe we have used the best practices in doing so:

- The properties were marked as deprecated in v1.2.2, see [changelog here](https://singroup.github.io/dscribe/latest/changelog.html).
- This breaking change in the naming was introduced when we bumped up our major version number from 1.x to 2.x: this indicates backwards incompatible changes.

As a user you have two options:

1. You can fix your dscribe dependency to version 1.x: your old scripts will work with this version.
2. You can choose to update your scripts to conform with 2.x

Hope this helps.
